<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */ __('Loading...') ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?= /* @escapeNotVerified */ $block->getSerializedCheckoutConfig() ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>");
            return url.setBaseUrl('<?= /* @escapeNotVerified */ $block->getBaseUrl() ?>');
        })
    </script>

    <script type="text/javascript">
            require(['jquery', 'jquery/ui','mage/mage'], function($){
                $( document ).ready(function() {
                        //wait until the last element (.payment-method) being rendered
                        var existCondition = setInterval(function() {
                         if ($('.payment-method._active').length) {
                          clearInterval(existCondition);
                          runMyFunction();
                         }
                        }, 100);

                        function runMyFunction(){
                            var activePaymentMethod = $('.payment-method._active .payment-method-title input[name="payment[method]"]').val();
                            if(window.checkoutConfig.quoteItemData.length ){
                                var i;
                                var count = 0;
                                for (i = 0; i < window.checkoutConfig.quoteItemData.length; i++) {
                                    if(window.checkoutConfig.quoteItemData[i]["is_payfast_recurring"] == 1){
                                        count++;
                                    }
                                }

                                if(activePaymentMethod != 'payfast' &&  count >= 1){
                                    $( ".payfastrecurringmsg"+activePaymentMethod+"" ).remove();
                                    $( ".payment-method._active .payment-method-content" ).prepend( '<div class="alert alert-warning payfastrecurringmsg'+activePaymentMethod+'">You must pay using PayFast checkout method as you are having recurring product in your cart.</div>' );
                                    $('.action.primary.checkout').attr("disabled", true);
                                }else{
                                    $('.action.primary.checkout').attr("disabled", false);
                                }
                            }

                            $("input[name='payment[method]']").click(function(){
                                var activePaymentMethod = $(this).val();
                                if(activePaymentMethod != 'payfast' &&  count >= 1){
                                    $( ".payfastrecurringmsg"+activePaymentMethod+"" ).remove();
                                    $( ".payment-method._active .payment-method-content" ).prepend( '<div class="alert alert-warning payfastrecurringmsg'+activePaymentMethod+'">You must pay using PayFast checkout method as you are having recurring product in your cart.</div>' );
                                    $('.action.primary.checkout').attr("disabled", true);
                                }else{
                                    $('.action.primary.checkout').attr("disabled", false);
                                }
                            });
                        }

                });
            });
    </script>
    <style>
    .alert-warning {
        color: #856404;
        background-color: #fff3cd;
        border-color: #ffeeba;
    }
    .alert {
        position: relative;
        padding: .75rem 1.25rem;
        margin-bottom: 1rem;
        border: 1px solid transparent;
        border-radius: .25rem;
    }
    </style>
</div>
