<?php
// @codingStandardsIgnoreFile
/** @var Payfast\Payfast\Block\Adminhtml\Payfast\Recurring\Payment\View\Tab\Charge $block */
$code = $this->escapeHtml($block->getMethodCode());
?>

<div class="form-inline">

    <form id="payment_form_<?php /* @noEscape */ echo $code; ?>" method="post" action="<?php echo $block->getChargeUrl()?>">
        <input type="hidden" name="form_key" value="<?php echo $block->getFormKey()?>">
        <div class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset">
                <div class="admin__field _required">
                    <label class="label admin__field-label" for="amount-field">
                        <span><?php echo $this->escapeHtml(__('Amount')); ?></span>
                    </label>
                    <div class="admin__field-control control">
                        <input class="admin__control-text" type="text" name="amount" aria-describedby="amount-field" id="amount" />
                    </div>
                </div>
            </fieldset>
        </div>

        <div class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset">
                <div class="admin__field _required">
                    <label class="label admin__field-label" for="amount-field">
                        <span><?php echo $this->escapeHtml(__('Description')); ?></span>
                    </label>
                    <div class="admin__field-control control">
                        <input class="admin__control-text" type="text" name="description" aria-describedby="description-field" id="description" />

                    </div>
                </div>
            </fieldset>
        </div>
        <div class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset">
                <div class="admin__field">
                    <div class="page-actions-buttons">
                        <button type="submit" name="Submit" class="save action- scalable primary">
                            <span>Submit</span>
                        </button>
                    </div>
                </div>
            </fieldset>
        </div>
    </form>
</div>

<script type="text/javascript">
    require(["jquery",
        'Magento_Ui/js/modal/alert',
        ],function($, alert) {

        $(document).ready(function() {

            var customurl = "<?php echo $block->getChargeUrl()?>";
            $('#payment_form_payfast').on('submit', function (e){
                e.preventDefault();
                console.log($(this).serialize());

                $.ajax({
                    url: customurl,
                    type: 'POST',
                    dataType: 'json',
                    data: $(this).serialize(),
                    beforeSend: function (){
                        $('body').trigger('processStart');
                    },
                    complete: function(result, status) {
                        $('body').trigger('processStop');
                        console.log(result.responseJSON.message, status, result);
                        alert({
                            content: result.responseJSON.message
                        });

                    },
                    error: function (xhr, status, error) {
                        $('body').trigger('processStop');
                        var err = eval("(" + xhr.responseText + ")");
                        // added error message
                        alert({ content: err });
                        //console.log(err.Message);
                    }

                });
            })

        });
    });
</script>
