<?php
// @codingStandardsIgnoreFile
/** @var Payfast\Payfast\Block\Adminhtml\Payfast\Recurring\Payment\View\Tab\Edit $block */
$code = $this->escapeHtml($block->getMethodCode());
?>

<div class="form-inline">
    <form id="payment_form_<?php /* @noEscape */ echo $code; ?>" method="post" action="<?php echo $block->getChargeUrl()?>">
        <input type="hidden" name="form_key" value="<?php echo $block->getFormKey()?>">
        <div class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset">
                <div class="admin__field _required">
                    <label class="label admin__field-label" for="amount-field">
                        <span><?php echo $this->escapeHtml(__('Amount')); ?></span>
                    </label>
                    <div class="admin__field-control control">
                        <input class="admin__control-text" type="text" name="amount" aria-describedby="amount-field" id="amount" />
                    </div>
                </div>
            </fieldset>
        </div>

        <div class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset">
                <div class="admin__field _required">
                    <label class="label admin__field-label" for="amount-field">
                        <span><?php echo $this->escapeHtml(__('Description')); ?></span>
                    </label>
                    <div class="admin__field-control control">
                        <input class="admin__control-text" type="text" name="description" aria-describedby="description-field" id="description" />

                    </div>
                </div>
            </fieldset>
        </div>
        <input type="submit" name="Submit" class="submit">
    </form>
</div>

<script type="text/javascript">
    require(["jquery"],function($) {
        $(document).ready(function() {
            var customurl = "<?php echo $block->getChargeUrl()?>";
            $.ajax({
                url: customurl,
                type: 'POST',
                dataType: 'json',
                data: {
                    customdata1: 'test1',
                    customdata2: 'test2',
                },
                complete: function(response) {
                    country = response.responseJSON.default_country;
                    state = response.responseJSON.state;
                    console.log(state+' '+country);
                },
                error: function (xhr, status, errorThrown) {
                    console.log('Error happens. Try again.');
                }
            });
        });
    });
</script>
