<?php
// @codingStandardsIgnoreFile
/** @var Payfast\Payfast\Block\Adminhtml\Payfast\Recurring\Payment\View\Tab\Edit $block */
$code = $this->escapeHtml($block->getMethodCode());
?>

<div class="form-inline">
    <form id="payment_form_<?php /* @noEscape */ echo $code; ?>" method="post" action="<?php echo $block->getChargeUrl()?>">
        <input type="hidden" name="form_key" value="<?php echo $block->getFormKey()?>">
        <div class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset">
                <div class="admin__field">
                    <label class="label admin__field-label" for="amount-field">
                        <span><?php echo $this->escapeHtml(__('Description')); ?></span>
                    </label>
                    <div class="admin__field-control control">
                        <?php echo $this->escapeHtml($block->getDescription()); ?>
                    </div>
                </div>
            </fieldset>
        </div>

        <div class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset">
                <div class="admin__field _required">
                    <label class="label admin__field-label" for="amount-field">
                        <span><?php echo $this->escapeHtml(__('Amount')); ?></span>
                    </label>
                    <div class="admin__field-control control">
                        <input class="admin__control-text" type="text" name="amount" aria-describedby="amount-field" id="amount" value="<?php echo $block->getAmount(); ?>" />
                    </div>
                </div>
            </fieldset>
        </div>

        <div class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset">
                <div class="admin__field _required">
                    <label class="label admin__field-label" for="frequency-field">
                        <span><?php echo $this->escapeHtml(__('Frequency')); ?></span>
                    </label>

                    <div class="admin__field-control control">

                            <select id="template_select" name="frequency" class="admin__control-select required-entry">
                            <?php foreach ($this->getOptions() as $option): ?>
                                <option value="<?= $this->escapeHtml($option['value']) ?>"
                                    <?= /* @noEscape */ $block->getFrequecy() == $option['value'] ?
                                        ' selected="selected"' : '' ?>><?= $this->escapeHtml($option['label']) ?>
                                </option>
                            <?php endforeach; ?>
                            </select>
                    </div>
                </div>
            </fieldset>
        </div>

        <div class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset">
                <div class="admin__field _required">
                    <label class="label admin__field-label" for="cycles-field">
                        <span><?php echo $this->escapeHtml(__('Cycles')); ?></span>
                    </label>
                    <div class="admin__field-control control">
                        <input class="admin__control-text" type="text" name="cycles" aria-describedby="cycles-field" id="cycles" value="<?php echo $block->getCycles(); ?>" />
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset">
                <div class="admin__field _required">
                    <label class="label admin__field-label" for="next_run-field">
                        <span><?php echo $this->escapeHtml(__('Run Date')); ?></span>
                    </label>
                    <div class="admin__field-control control">
                        <?php echo $block->getNextRunDate() ?>
                    </div>
                </div>
            </fieldset>
        </div>

        <div class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset">
                <div class="admin__field _required">
                        <div class="page-actions-buttons">
                            <button type="submit" name="Submit" class="save action- scalable primary">
                                <span>Submit</span>
                            </button>
                        </div>
                </div>
            </fieldset>
        </div>

    </form>
</div>
<script type="text/javascript">
    require(["jquery",
        'Magento_Ui/js/modal/alert',
    ],function($, alert) {

        $(document).ready(function() {

            var customurl = "<?php echo $block->getChargeUrl()?>";
            $('#payment_form_payfast').on('submit', function (e){
                e.preventDefault();
                console.log($(this).serialize());

                $.ajax({
                    url: customurl,
                    type: 'POST',
                    dataType: 'json',
                    data: $(this).serialize(),
                    beforeSend: function (){
                        $('body').trigger('processStart');
                    },
                    complete: function(result, status) {
                        $('body').trigger('processStop');

                        alert({
                            content: result.responseJSON.message
                        });
                    },
                    error: function (xhr, status, error) {
                        $('body').trigger('processStop');
                        var err = eval("(" + xhr.responseText + ")");
                        // added error message
                        alert({ content: err });
                        //console.log(err.Message);
                    }

                });
            })

        });
    });
</script>
