
<script>
    require([
        'jquery',
        'uiRegistry'
    ], function ($, uiRegistry) {

        $(document).ready(function () {
            var self = this;

            uiRegistry.get('product_form.product_form.payfast-recurring-payment.container_subscription_type.subscription_type', function (element){
                console.log('subscription type value is ', element.initialValue);
                if (element.initialValue === '2') {
                    self.hideSubscriptionFields();
                }
            });

            $(document).on("click", "div[data-index='payfast-recurring-payment']", function () {

                $("select[name='product[subscription_type]']").on('change', function(){
                    let type = uiRegistry.get('product_form.product_form.payfast-recurring-payment.container_subscription_type.subscription_type').value();
                    if (parseInt(type) === 2) {
                        self.hideSubscriptionFields();
                    } else {
                        self.showSubscriptionFields();
                    }
               })
            });

            self.hideSubscriptionFields = function () {
                uiRegistry.get('index = pf_billing_period_max_cycles').hide();
                uiRegistry.get('index = pf_billing_period_frequency').hide();
                uiRegistry.get('index = pf_initial_amount').hide();
                uiRegistry.get('index = pf_is_start_date_editable').hide();
            }

            self.showSubscriptionFields= function() {
                uiRegistry.get('index = pf_billing_period_max_cycles').show();
                uiRegistry.get('index = pf_billing_period_frequency').show();
                uiRegistry.get('index = pf_initial_amount').show();
                uiRegistry.get('index = pf_is_start_date_editable').show();
            }

        });
    });
</script>
