<?php if ($this->getIsAddress()) : ?>
    <?php foreach ($this->getRenderedInfo() as $row) : ?>
        <address><?= nl2br($this->getObjectData($row, 'value')) ?></address>
    <?php endforeach; ?>

<?php else : ?>
    <table class="data table">
        <caption class="table-caption"><?= /* @noEscape */ __('PayFast Recurring Payment'); ?></caption>
        <tbody>
            <?php foreach ($this->getRenderedInfo() as $row) : ?>
                <tr>
                    <th class="col label" scope="row"><span><?= $this->escapeHtml($this->getObjectData($row, 'label')) ?>:</span></th>
                    <td class="col value" style="padding-top: 11px;"><span><?= $this->renderRowValue($row) ?></span></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
