<?php $actionname = (!empty($this->getRequest()->getActionName())) ? $this->getRequest()->getActionName() : '';  ?>
<div class="order-paypal-recurring-payment-details">
    <?php /* info tabs */ ?>
    <?php $layout = $this->getLayout(); ?>
    <?php $infoTabs = $this->getGroupChildNames('info_tabs');?>

    <div class="actions-toolbar order-actions-toolbar">
        <div class="primary">
            <?php if ($this->getCanActivate()): ?>
                <button type="button" title="<?= /* @noEscape */ __('Activate') ?>" class="action activate"
                        onclick="if( confirm('<?= /* @noEscape */ $this->getConfirmationMessage() ?>') ) { window.location.href = '<?= /* @noEscape */ $this->getActivateUrl() ?>'; } return false;">
                    <span><?= /* @noEscape */ __('Activate') ?></span>
                </button>
            <?php endif; ?>
            <?php if ($this->getCanCancel()): ?>
                <button type="button" title="<?= /* @noEscape */ __('Cancel') ?>" class="action cancel"
                        onclick="if( confirm('<?= /* @noEscape */ $this->getConfirmationMessage() ?>') ) { window.location.href = '<?= /* @noEscape */ $this->getCancelUrl() ?>'; } return false;">
                    <span><?= /* @noEscape */ __('Cancel') ?></span>
                </button>
            <?php endif; ?>
            <?php if ($this->getCanSuspend()): ?>
                <button type="button" title="<?= /* @noEscape */ __('Suspend') ?>" class="action suspend"
                        onclick="if( confirm('<?= /* @noEscape */ $this->getConfirmationMessage() ?>') ) { window.location.href = '<?= /* @noEscape */ $this->getSuspendUrl() ?>'; } return false;">
                    <span><?= /* @noEscape */ __('Suspend') ?></span>
                </button>
            <?php endif; ?>
            <?php if ($this->getCanUpdate()): ?>
                <button type="button" title="<?= /* @noEscape */ __('Get Update') ?>" class="action update"
                        onclick="if( confirm('<?= /* @noEscape */ $this->getConfirmationMessage() ?>') ) { window.location.href = '<?= /* @noEscape */ $this->getUpdateUrl() ?>'; } return false;">
                    <span><?= /* @noEscape */ __('Get Update') ?></span>
                </button>
            <?php endif; ?>
        </div>
    </div>

    <ul id="order-info-tabs" class="items order-links">
        <?php foreach ($infoTabs as $elementName): ?>
            <?php $block = $layout->getBlock($elementName); ?>
            <?php if (!$block):
                continue;
            endif; ?>
            <?php if ($this->getObjectData($block, 'is_view_current')): ?>
                <li class="nav item current">
                    <strong><?= $this->escapeHtml($this->getObjectData($block, 'view_label')) ?></strong>
                </li>
            <?php else: ?>
                <li class="nav item">
                    <a href="<?= $this->escapeHtml($this->getObjectData($block, 'view_url')) ?>">
                        <?= $this->escapeHtml($this->getObjectData($block, 'view_label')) ?>
                    </a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>

    <div class="order-details-items" <?= (!empty($actionname) && $actionname != 'orders') ? 'style="display:block"' : 'style="display:none"'; ?>>
        <?php for ($i = 1; $i <= 3; $i++): ?>
            <?php $infoBlocks = $this->getGroupChildNames("info_blocks_row_{$i}"); ?>
            <?php if ($infoBlocks): ?>
                <div class="block block-view-info">
                    <div class="block-content">
                        <?php for ($j = 1; $j <= 2; $j++): ?>
                            <?php foreach ($infoBlocks as $elementName): ?>
                                <?php $block = $layout->getBlock($elementName); ?>
                                <?php if (!$block):
                                    continue;
                                endif; ?>
                                <?php if ($j == $this->getObjectData($block, 'view_column')): ?>
                                    <div class="box box<?= /* @noEscape */ $j ?>">
                                        <strong class="box-title">
                                            <span><?= $this->escapeHtml($this->getObjectData($block, 'view_label')) ?></span>
                                        </strong>

                                        <div class="box-content">
                                            <?php $html = $layout->renderElement($elementName); ?>
                                            <?=/* @noEscape */ ($html ? $html : __('No information available.')); ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        <?php endfor; ?>
                    </div>
                </div>
            <?php endif; ?>
        <?php endfor; ?>
    </div>

    <!-- table data block -->
    <?php $table = $this->getChildBlock('table') ?>
    <?php if ($table): ?>
        <div class="order-details-items block block-payFast-recurring-details-items">
            <div class="block-title">
                <strong><?= $this->escapeHtml($this->getObjectData($table, 'view_label')) ?></strong>
            </div>
            <div class="block-content">
                <?= $this->getChildHtml('table') ?>
            </div>
        </div>
    <?php endif; ?>

    <div class="actions-toolbar">
        <div class="secondary">
            <a href="<?= $block->escapeUrl($this->getBackUrl()) ?>" class="action back">
                <span><?= /* @noEscape */ __('Back to PayFast Recurring Billing Payments') ?></span>
            </a>
        </div>
    </div>
</div>
